"""The downloadable study pack.

The pack is rendered as a print-designed HTML document and converted to PDF by
the headless browser already present on the machine (Chrome or Edge).

Why a browser rather than a PDF library: Hindi and Bangla need complex-script
shaping — reordered matras, conjuncts, ligatures. A text-drawing PDF library
places glyphs in code-point order and produces subtly wrong Devanagari. The
browser uses HarfBuzz and gets it right, which matters when the entire point of
the product is that a student can study in their own language.

If no browser is found the HTML is returned instead, which the student can still
read and print. Nothing here costs money or leaves the machine.
"""

from __future__ import annotations

import base64
import html
import logging
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger("luminara.export")

BROWSERS = [
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
]

LANGUAGE_HEADINGS = {
    "en": {
        "pack": "Study pack",
        "summary": "Summary",
        "concepts": "Key concepts",
        "points": "Important points",
        "formulas": "Formulas",
        "visuals": "What was on the board",
        "terms": "Technical terms",
        "simple": "In simple words",
        "script": "Lecture script",
        "board_only": "Written on the board, never said aloud",
        "sources": "Sources",
        "generated": "Generated by Luminara",
    },
    "hi": {
        "pack": "अध्ययन सामग्री",
        "summary": "सारांश",
        "concepts": "मुख्य अवधारणाएँ",
        "points": "महत्वपूर्ण बिंदु",
        "formulas": "सूत्र",
        "visuals": "बोर्ड पर क्या था",
        "terms": "तकनीकी शब्द",
        "simple": "सरल शब्दों में",
        "script": "व्याख्यान की लिपि",
        "board_only": "बोर्ड पर लिखा गया, कहा नहीं गया",
        "sources": "स्रोत",
        "generated": "Luminara द्वारा तैयार",
    },
    "bn": {
        "pack": "অধ্যয়ন প্যাক",
        "summary": "সারসংক্ষেপ",
        "concepts": "মূল ধারণা",
        "points": "গুরুত্বপূর্ণ পয়েন্ট",
        "formulas": "সূত্র",
        "visuals": "বোর্ডে যা ছিল",
        "terms": "কারিগরি শব্দ",
        "simple": "সহজ ভাষায়",
        "script": "লেকচার স্ক্রিপ্ট",
        "board_only": "বোর্ডে লেখা, বলা হয়নি",
        "sources": "সূত্রসমূহ",
        "generated": "Luminara দ্বারা তৈরি",
    },
    "ar": {
        "pack": "حزمة الدراسة",
        "summary": "الملخص",
        "concepts": "المفاهيم الأساسية",
        "points": "نقاط مهمة",
        "formulas": "الصيغ",
        "visuals": "ما كان على السبورة",
        "terms": "المصطلحات التقنية",
        "simple": "بكلمات بسيطة",
        "script": "نص المحاضرة",
        "board_only": "مكتوب على السبورة ولم يُقل",
        "sources": "المصادر",
        "generated": "أُنشئ بواسطة Luminara",
    },
}

CSS = """
@page { size: A4; margin: 18mm 16mm 20mm 16mm; }
* { box-sizing: border-box; }
body {
  font-family: "Segoe UI", "Nirmala UI", "Noto Sans", system-ui, -apple-system, sans-serif;
  color: #16181d; margin: 0; font-size: 11.2pt; line-height: 1.62;
  -webkit-print-color-adjust: exact; print-color-adjust: exact;
}
h1, h2, h3 { margin: 0; font-weight: 650; letter-spacing: -0.01em; }
.cover { padding: 26mm 0 14mm 0; border-bottom: 2.5pt solid #6D4CFF; margin-bottom: 12mm; }
.mark { display: flex; align-items: center; gap: 9px; margin-bottom: 16mm; }
.dot { width: 13px; height: 13px; border-radius: 50%;
       background: linear-gradient(135deg,#6D4CFF,#22C7A9); }
.brand { font-size: 12pt; font-weight: 700; letter-spacing: 0.02em; color: #6D4CFF; }
.kicker { font-size: 8.6pt; letter-spacing: 0.16em; text-transform: uppercase;
          color: #7A8095; margin-bottom: 6px; }
h1 { font-size: 27pt; line-height: 1.16; margin-bottom: 8px; }
.course { font-size: 12pt; color: #555b6b; }
.meta { margin-top: 10mm; display: flex; flex-wrap: wrap; gap: 7px; }
.pill { border: 1px solid #d9dce6; border-radius: 999px; padding: 4px 11px;
        font-size: 8.8pt; color: #4a5060; background: #f7f8fc; }
section { margin-bottom: 9mm; page-break-inside: avoid; }
h2 { font-size: 14.5pt; margin-bottom: 5mm; padding-bottom: 2.5mm;
     border-bottom: 1px solid #e6e8f0; color: #16181d; }
h3 { font-size: 11.6pt; color: #4B33C4; margin-bottom: 2mm; }
p { margin: 0 0 3.5mm 0; }
.concept { margin-bottom: 6mm; page-break-inside: avoid; }
.src { margin-top: 2mm; display: flex; flex-wrap: wrap; gap: 5px; align-items: center; }
/* flex: 0 0 auto stops a crowded row from squeezing a chip into an ellipse */
.chip { font-size: 8pt; border-radius: 999px; padding: 2.5px 8px; flex: 0 0 auto;
        white-space: nowrap; line-height: 1.5;
        border: 1px solid #d9dce6; color: #5a6070; background: #fafbff; }
.chip.speech { border-color:#9fe3d5; background:#f0fbf8; color:#12796a; }
.chip.board  { border-color:#f3d5a8; background:#fffaf1; color:#96631a; }
.chip.formula{ border-color:#f0b8c1; background:#fff5f7; color:#a32c40; }
ul { margin: 0 0 3mm 0; padding-left: 5.5mm; }
li { margin-bottom: 2.2mm; }
/* named -card so it cannot collide with the `.chip.formula` source chip */
.formula-card { border: 1px solid #f0b8c1; background: #fff7f9; border-radius: 8px;
           padding: 4.5mm 5mm; margin-bottom: 4mm; page-break-inside: avoid; }
.formula-card .expr { font-family: "Cascadia Mono", Consolas, "Courier New", monospace;
                 font-size: 14pt; font-weight: 600; color: #a32c40; }
.formula-card .meaning { font-size: 10.2pt; color: #4a5060; margin-top: 2.5mm; }
.terms { width: 100%; border-collapse: collapse; }
.terms td { padding: 2.4mm 0; border-bottom: 1px solid #eef0f6; vertical-align: top; }
.terms td.t { width: 34%; font-weight: 600; color: #12796a;
              font-family: "Cascadia Mono", Consolas, monospace; font-size: 10pt; }
.board-img { width: 100%; border: 1px solid #e2e5ee; border-radius: 8px; margin-bottom: 4mm; }
.boardtext { font-family: "Cascadia Mono", Consolas, monospace; font-size: 9.2pt;
             white-space: pre-wrap; background: #fbfbfe; border: 1px solid #e6e8f0;
             border-radius: 8px; padding: 4mm; color: #3c4252; }
.script { page-break-before: always; }
.line { display: flex; gap: 4.5mm; padding: 1.8mm 0; border-bottom: 1px solid #f2f3f8;
        page-break-inside: avoid; }
.tc { font-family: "Cascadia Mono", Consolas, monospace; font-size: 9pt; color: #12796a;
      min-width: 13mm; padding-top: 0.6mm; }
.line .txt { flex: 1; }
.marker { font-size: 8.4pt; color: #96631a; margin-top: 1.2mm; }
.simple { background: #f6f4ff; border-left: 3px solid #6D4CFF; border-radius: 0 8px 8px 0;
          padding: 4.5mm 5mm; }
footer { margin-top: 12mm; padding-top: 4mm; border-top: 1px solid #e6e8f0;
         font-size: 8.4pt; color: #8a90a2; }
"""


def _e(value) -> str:
    return html.escape(str(value or ""))


def _chips(sources: list[dict]) -> str:
    if not sources:
        return ""
    out = []
    for source in sources[:4]:
        kind = str(source.get("type", "")).lower()
        cls = "speech" if kind == "speech" else "formula" if kind == "formula" else "board"
        label = kind.replace("_", " ").title()
        ref = source.get("ref", "")
        text = f"{label} · {ref}" if ref and ref.lower() != kind else label
        out.append(f'<span class="chip {cls}">{_e(text)}</span>')
    return f'<div class="src">{"".join(out)}</div>'


def render_html(
    knowledge: dict,
    script_doc: dict,
    *,
    language: str = "en",
    course: str = "",
    engines: dict | None = None,
    board_image: Path | None = None,
    board_text: str = "",
) -> str:
    t = LANGUAGE_HEADINGS.get(language, LANGUAGE_HEADINGS["en"])
    rtl = language == "ar"
    parts: list[str] = []

    # ---- cover -----------------------------------------------------------
    pills = [t["pack"], datetime.now(timezone.utc).strftime("%d %b %Y")]
    if script_doc.get("duration_sec"):
        pills.append(f"{int(script_doc['duration_sec'])}s")
    if knowledge.get("formulas"):
        pills.append(f"{len(knowledge['formulas'])} × {t['formulas']}")
    parts.append(
        f"""
<div class="cover">
  <div class="mark"><div class="dot"></div><div class="brand">LUMINARA</div></div>
  <div class="kicker">{_e(t['pack'])}</div>
  <h1>{_e(knowledge.get('title', 'Lecture'))}</h1>
  <div class="course">{_e(course)}</div>
  <div class="meta">{''.join(f'<span class="pill">{_e(p)}</span>' for p in pills)}</div>
</div>"""
    )

    if knowledge.get("summary"):
        parts.append(
            f"<section><h2>{_e(t['summary'])}</h2><p>{_e(knowledge['summary'])}</p></section>"
        )

    if knowledge.get("key_concepts"):
        blocks = "".join(
            f'<div class="concept"><h3>{_e(c.get("name"))}</h3>'
            f'<p>{_e(c.get("explanation"))}</p>{_chips(c.get("sources") or [])}</div>'
            for c in knowledge["key_concepts"]
        )
        parts.append(f"<section><h2>{_e(t['concepts'])}</h2>{blocks}</section>")

    if knowledge.get("important_points"):
        items = "".join(
            f'<li>{_e(p.get("text"))}{_chips(p.get("sources") or [])}</li>'
            for p in knowledge["important_points"]
        )
        parts.append(f"<section><h2>{_e(t['points'])}</h2><ul>{items}</ul></section>")

    if knowledge.get("formulas"):
        blocks = "".join(
            f'<div class="formula-card"><div class="expr">{_e(f.get("plain") or f.get("latex"))}</div>'
            f'<div class="meaning">{_e(f.get("meaning"))}</div>'
            f'{_chips([{"type": "formula", "ref": f.get("source_ref", "Whiteboard")}])}</div>'
            for f in knowledge["formulas"]
        )
        parts.append(f"<section><h2>{_e(t['formulas'])}</h2>{blocks}</section>")

    visuals = knowledge.get("visual_explanations") or []
    if visuals or board_image or board_text:
        inner = ""
        if board_image and board_image.exists():
            try:
                data = base64.b64encode(board_image.read_bytes()).decode("ascii")
                mime = "image/png" if board_image.suffix.lower() == ".png" else "image/jpeg"
                inner += f'<img class="board-img" src="data:{mime};base64,{data}" />'
            except Exception as exc:
                log.warning("could not embed board image: %s", exc)
        for visual in visuals:
            inner += (
                f'<div class="concept"><h3>{_e(visual.get("title"))}</h3>'
                f'<p>{_e(visual.get("explanation"))}</p>'
                f'{_chips([{"type": "diagram", "ref": visual.get("source_ref", "Whiteboard")}])}</div>'
            )
        if board_text:
            inner += f'<div class="boardtext">{_e(board_text)}</div>'
        parts.append(f"<section><h2>{_e(t['visuals'])}</h2>{inner}</section>")

    if knowledge.get("technical_terms"):
        rows = "".join(
            f'<tr><td class="t">{_e(term.get("term"))}</td>'
            f'<td>{_e(term.get("definition"))}</td></tr>'
            for term in knowledge["technical_terms"]
        )
        parts.append(
            f"<section><h2>{_e(t['terms'])}</h2><table class=\"terms\">{rows}</table></section>"
        )

    if knowledge.get("simple_explanation"):
        parts.append(
            f"<section><h2>{_e(t['simple'])}</h2>"
            f'<div class="simple">{_e(knowledge["simple_explanation"])}</div></section>'
        )

    # ---- script ----------------------------------------------------------
    if script_doc.get("entries"):
        lines = ""
        for entry in script_doc["entries"]:
            marker = ""
            board = [r for r in entry.get("related", []) if r.get("kind") == "board"]
            if board:
                marker = (
                    f'<div class="marker">↳ {_e(t["board_only"])}: '
                    f'{_e(board[0].get("detail") or board[0].get("label"))}</div>'
                )
            lines += (
                f'<div class="line"><div class="tc">{_e(entry["timecode"])}</div>'
                f'<div class="txt">{_e(entry["text"])}{marker}</div></div>'
            )
        parts.append(f'<section class="script"><h2>{_e(t["script"])}</h2>{lines}</section>')

    if script_doc.get("board_only"):
        items = "".join(
            f'<li><strong>{_e(b.get("label"))}</strong> — {_e(b.get("detail"))}</li>'
            for b in script_doc["board_only"]
        )
        parts.append(f"<section><h2>{_e(t['board_only'])}</h2><ul>{items}</ul></section>")

    engine_line = ""
    if engines:
        engine_line = " · ".join(f"{k}: {v}" for k, v in engines.items() if v)

    parts.append(
        f"""<footer>{_e(t['generated'])} — {_e(engine_line)}<br>
Formulas and technical terms are reproduced exactly as they appeared in the lecture
and are never translated.</footer>"""
    )

    direction = ' dir="rtl"' if rtl else ""
    return f"""<!DOCTYPE html>
<html lang="{_e(language)}"{direction}>
<head><meta charset="utf-8"><title>{_e(knowledge.get('title', 'Lecture'))} — Luminara</title>
<style>{CSS}</style></head>
<body>{''.join(parts)}</body></html>"""


# ---------------------------------------------------------------------------
# PDF conversion
# ---------------------------------------------------------------------------


def find_browser() -> str | None:
    for candidate in BROWSERS:
        if Path(candidate).exists():
            return candidate
    for name in ("chrome", "msedge", "chromium", "google-chrome"):
        found = shutil.which(name)
        if found:
            return found
    return None


def html_to_pdf(html_text: str, out_path: Path, timeout: int = 90) -> bool:
    """Convert with the local headless browser. Returns False if unavailable."""
    browser = find_browser()
    if not browser:
        log.warning("no Chrome/Edge found; cannot render PDF")
        return False

    with tempfile.TemporaryDirectory(prefix="luminara-pdf-") as tmp:
        source = Path(tmp) / "studypack.html"
        source.write_text(html_text, encoding="utf-8")
        profile = Path(tmp) / "profile"

        base_args = [
            browser,
            "--disable-gpu",
            "--no-sandbox",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-extensions",
            f"--user-data-dir={profile}",
            "--no-pdf-header-footer",
            "--run-all-compositor-stages-before-draw",
            "--virtual-time-budget=8000",
            f"--print-to-pdf={out_path}",
            source.as_uri(),
        ]

        for headless in ("--headless=new", "--headless"):
            args = [base_args[0], headless] + base_args[1:]
            try:
                result = subprocess.run(args, capture_output=True, timeout=timeout)
            except subprocess.TimeoutExpired:
                log.warning("headless print timed out with %s", headless)
                continue
            if out_path.exists() and out_path.stat().st_size > 1024:
                return True
            log.warning(
                "headless print produced nothing with %s: %s",
                headless,
                (result.stderr or b"").decode("utf-8", "ignore")[:300],
            )
    return False
